
-- Create table for storing director report files
CREATE TABLE IF NOT EXISTS public.director_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  test_result_id BIGINT NOT NULL,
  file_path TEXT NOT NULL,
  viewed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create a storage bucket for test result PDFs
INSERT INTO storage.buckets (id, name, public)
VALUES ('test-results', 'Test Results PDFs', FALSE)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to upload to the test-results bucket
CREATE POLICY "Users can upload test results" 
ON storage.objects 
FOR INSERT 
TO authenticated 
WITH CHECK (bucket_id = 'test-results');

-- Allow directors to read test results
CREATE POLICY "Directors can view test results" 
ON storage.objects 
FOR SELECT 
TO authenticated 
USING (
  bucket_id = 'test-results' AND 
  EXISTS (
    SELECT 1 FROM public.users 
    WHERE id::text = auth.uid() AND role = 'director'
  )
);
